namespace: dev-traffic-control

configMapGenerator:
- envs:
  - environment.env
  name: environment
generatorOptions:
  disableNameSuffixHash: true

#configurations:
#- configuration.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

replacements:
- source:
    fieldPath: data.NAMESPACE_ZIPKIN
    kind: ConfigMap
    name: environment
    version: v1
  targets:
  - fieldPaths:
    - spec.tracing.zipkin.endpointAddress
    options:
      delimiter: .
      index: 1
    select:
      group: dapr.io
      kind: Configuration
      name: appconfig
      version: v1alpha1
