apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: actorStateStore
    value: "true"
  - name: redisHost
    value: ""
  - name: redisPassword
    value: ""
# Commented out secretKeyRef below to use hardcoded redisPassword above as
# not sure how dapr can get redis-password from namespace=redis
# while state.redis is deployed in a different namespace
#    secretKeyRef:
#      name: redis
#      key: redis-password
#auth:
#  secretStore: kubernetes
scopes:
  - trafficcontrolservice
