apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.NAMESPACE_ZIPKIN_PLACEHOLDER.svc.cluster.local:9411/api/v2/spans"
