apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dapr-appconfig-zipkin.yaml
#  - dapr-pubsub-kafka.yaml
  - dapr-pubsub-redis.yaml
#  - dapr-pubsub-rabbitmq.yaml
  - dapr-statestore-redis.yaml
  - dapr-secretstore-k8s.yaml
  - k8s-serviceaccount-rbac-secretstore.yaml
  - k8s-secret-traffic-control-license-key.yaml
  - zipkin.yaml
  - finecollectionservice-deployment.yaml
  - finecollectionservice-service.yaml
  - simulation-deployment.yaml
  - trafficcontrolservice-deployment.yaml
  - trafficcontrolservice-service.yaml
  - vehicleregistrationservice-deployment.yaml
  - vehicleregistrationservice.yaml
