apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: environment
  envs:
  - environment.env
generatorOptions:
  disableNameSuffixHash: true

resources:
  - dapr-appconfig-zipkin.yaml
  - dapr-pubsub-kafka.yaml
  - dapr-statestore-redis.yaml
  - dapr-secretstore-k8s.yaml
  - k8s-serviceaccount-rbac-secretstore.yaml
  - k8s-secret-traffic-control-license-key.yaml
  - zipkin.yaml
  - finecollectionservice-deployment.yaml
  - finecollectionservice-service.yaml
  - simulation-deployment.yaml
  - trafficcontrolservice-deployment.yaml
  - trafficcontrolservice-service.yaml
  - vehicleregistrationservice-deployment.yaml
  - vehicleregistrationservice.yaml

# Extract the variables out of the ConfigMap and into Kustomize variables
vars:
  - name: NAMESPACE_ZIPKIN
    objref:
      kind: ConfigMap
      name: environment
      apiVersion: v1
      #namespace: dev-traffic-control
    fieldref:
      fieldpath: data.NAMESPACE_ZIPKIN
# Add any additional variables that are used

# Add additional varReference entries if needed (custom CRDs, extra fields to substitute into, etc.)
configurations:
  - configuration.yaml