apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simulation
  name: simulation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulation
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simulation
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "simulationservice"
        # dapr.io/app-port: "6003"
        dapr.io/config: "appconfig"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - image: geepsah/simulation:latest
        name: simulation
        resources: {}
        env:
        - name: TRAFFIC_CONTROL_SERVICE
          value: trafficcontrolservice
status: {}
