apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: dapr-traffic-control
resources:
  - dapr-appconfig-zipkin.yaml
  - dapr-pubsub-kafka.yaml
  - dapr-secretstore-k8s.yaml
  - dapr-statestore-redis.yaml
  - zipkin.yaml
  - finecollectionservice-deployment.yaml
  - finecollectionservice-service.yaml
  - simulation-deployment.yaml
  - trafficcontrolservice-deployment.yaml
  - trafficcontrolservice-service.yaml
  - vehicleregistrationservice-deployment.yaml
  - vehicleregistrationservice.yaml